### PR TITLE
fix price stream connection handling

### PR DESCRIPTION
**Pull request by ersingencturk**
proper use of async void (see : https://www.jweiler.com/dont-use-async-void-in-your-code/)
proper handling of connection exceptions

### CODE REVIEW

**Comment by mrchrisok** [comment]
Turk,

Thanks for the PR.

The change to StreamSession.cs make sense.

The change to RestStream.cs is incomplete (only 1 of 2 catch blocks edited) and arguably unnecessary.
The CLR will automatically throw any errors (and inner exceptions) that occur in a catch block.
Presumably clients that use OkonkwoOandaV20 will be configured to log the full exception tree.
If you have a different view on this, let me know.
If not, then resubmit the PR minus the RestStream change.

Chris

**Comment by mrchrisok** [comment]
Turk,

Your PR correctly pointed out that StreamSession.StartSession() needed a correction to return 'Task' instead of 'void'. 

Thanks.

Re. your "... since that exception won't go up properly in the stack due to way you are using async methods ... ", please explain why this will remain the case after the correction to return 'Task'.

Thanks,
Chris

**Comment by ersingencturk** [comment]
using a task there is not changing the fact that you are not checking nullable variables before you access them that’s why

**Comment by mrchrisok** [comment]
Thanks Turk.

**Pull request closed without merging**
